#!/usr/bin/env ruby
# Stands for collins-ssh-root
# Fetch root credentials from collins for a given server
# then log into it via ssh (without requiring keys to be set up)

require 'collins_auth'
require 'yaml'
require 'optparse'

@options = {
  :password_attr => :system_password,
  :collins_timeout => 10,
  :background => false,
}

OptionParser.new do |opts|
  opts.banner = "#{$0}: Connects to assets over SSH as root with creds from collins"
  opts.separator "Usage: #{$0} [hostname]|[-t 001234]"
  opts.on('-t','--tag TAG',String,'SSH to the asset with TAG') {|v| @options[:tag] = v}
  opts.on('-p','--attribute ATTR',String,"Use collins attribute ATTR (Default: #{@options[:password_attr]})") {|v| @options[:password_attr] = v.to_sym}
  opts.on('-b','--background COMMAND',String,"Nohups command and fires it off in the background, immediately terminating session") {|v| @options[:cmd] = v ; @options[:background] = true }
  opts.on('-h','--help','Show help message') { puts opts ; exit 0 }
end.parse!

# if no tag given, require a hostname on argv
@options[:hostname] = ARGV.shift if @options[:tag].nil?
# if we werent given a background command, and there were remaining arguments, use those as a command
if @options[:cmd].nil? && !ARGV.empty?
  @options[:cmd] = ARGV.join(' ')
end

abort "Give me a hostname or tag to connect to" if @options[:hostname].nil? and @options[:tag].nil?

begin
  collins = Collins::Authenticator.setup_client timeout: @options[:collins_timeout]
rescue => e
  abort "Unable to set up collins client! #{e.message}"
end

begin
  node = if @options[:tag].nil?
    assets = collins.find(:hostname => @options[:hostname], :details => true)
    raise "More than 1 node found like #{@options[:hostname]} (found #{assets.length}). Please be more specific...\n#{assets.map {|a| a.hostname}.join "\n"}\n" if assets.length > 1
    raise "No assets found matching #{@options[:hostname]}" if assets.empty?
    assets.first
  else
    node = collins.get(@options[:tag])
    raise "No asset found with tag #{@options[:tag]}" if node.nil?
    node
  end
rescue => e
  abort "Error querying collins: #{e.message}"
end

# set the password in the env instead of letting it sit on the command line
ENV['SYSTEM_P'] = node.send(@options[:password_attr])
ENV['SYSTEM_H'] = node.addresses.first.address
ENV['SYSTEM_CMD'] = ''

ENV['SYSTEM_CMD'] = @options[:cmd] if !@options[:cmd].nil?
if @options[:background]
  ENV['SYSTEM_CMD'] = %Q( ( #{@options[:cmd]} ) &>/dev/null & )
  puts "ssh root@#{node.hostname} -- #{ENV['SYSTEM_CMD']}"
end
puts "ssh root@#{node.hostname} #{ENV['SYSTEM_CMD']}"
ssh_opts = '-t' if @options[:cmd].nil?

exec <<_EXPECT_
/usr/bin/expect -c '
spawn -noecho /usr/bin/ssh #{ssh_opts} -oUserKnownHostsFile=/dev/null -lroot "$env(SYSTEM_H)" -- "$env(SYSTEM_CMD)"
set timeout 30
expect {
  "Are you sure you want to continue connecting (yes/no)?" {
    send -- "yes\\r"
    expect {
      "assword:" {
        send -- "$env(SYSTEM_P)\\r"
      }
      default {
        puts "Didnt get a login prompt"
        exit 1
      }
    }
  }
  default {
    puts "Didnt get a SSH prompt"
    exit 1
  }
}
interact
'
_EXPECT_

